# for code generation
required = [
    "k8s.io/code-generator/cmd/deepcopy-gen",
    "sigs.k8s.io/controller-tools/cmd/controller-gen"
]

[[constraint]]
  branch = "master"
  name = "k8s.io/code-generator"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.11.2"

### Force the 1.11 version everywhere
[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "sigs.k8s.io/controller-tools"
  version = "v0.1.6"

### These overrides have been manually imported grom the Godeps/Godeps.json
### in the kubernetes-1.11 source tree
[[override]]
  name = "github.com/coreos/etcd"
  version = "v3.2.13"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.4-2-g300106c"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/MakeNowJust/heredoc"
  revision = "bb23615498cded5e105af4ce27de75b089cbe851"

[[override]]
  name = "github.com/docker/libnetwork"
  revision = "ba46b928444931e6865d8618dc03622cac79aa6f"

[[override]]
  name = "github.com/vishvananda/netlink"
  revision = "f67b75edbf5e3bb7dfe70bb788610693a71be3d1"

[[override]]
  name = "github.com/vishvananda/netns"
  revision = "be1fbeda19366dea804f00efff2dd73a1642fdcc"

[[override]]
  name = "golang.org/x/crypto"
  revision = "49796115aa4b964c318aad4f3084fdb41e9aa067"

# fix for a crash in "dep" (see https://github.com/golang/dep/issues/1799)
[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[prune]
  unused-packages = true
  go-tests = true
